### PR TITLE
Fix #114: fmt error if TF_CLI_ARGS* in env

### LINKED ISSUE #114: Set `TF_CLI_ARGS_fmt` to avoid errors when it is already in the environment
I use `TF_CLI_ARGS_fmt=<path>`, which points `terraform fmt` at the correct path without me having to specify it.

Unfortunately, it means it doesn't work with `vim-terraform`, since the executed command becomes `terraform fmt <path> <path>` and I get an error about only one arg being accepted.

To fix this issue, `vim-terraform` could either:
- run with `TF_CLI_ARGS_fmt=` blanked
- set `TF_CLI_ARGS_FMT=<path>` itself, and run with vanilla `terraform fmt`

### PR DESCRIPTION
**Pull request by OJFord**
If TF_CLI_ARGS or TF_CLI_ARGS_fmt env vars are used formatting may fail with invalid args. For example, `TF_CLI_ARGS_fmt=<tf_dir>` may be desirable for running outside of vim, but when vim-terraform adds thcalls `terraform fmt <tf_dir>` will cause it to fail due to twice listing the directory when only a single argument is expected.

This commit addresses the issue by ensuring no args come from the environment when vim-terraform calls fmt.

### CODE REVIEW

**Comment by dimbleby** [comment]
This is going to be broken for eg Windows users, isn't it?

If there's an easy cross-platform way of setting this environment variable empty then I guess I'm in favour of doing that.  

But I'd be reluctant to take on significant complication to deal with this; it seems to me like a bit of an edge case for which "don't do that" is not an unreasonable answer.

**Comment by OJFord** [comment]
@dimbleby Thanks, good point, fixed.

**Comment by dimbleby** [comment]
Well that's simple enough!

Sorry to be a pain, but: even better, I think, would be to put this at the top level of this file, eg just before `terraform#fmt`.  Then by the magic of autoloading we'll only execute this once, rather than every time we format.

**Comment by dimbleby** [comment]
Looks good, many thanks!

**Pull request merged**
