### PR TITLE
add google_project_iam_binding

### PR DESCRIPTION
**Pull request by mkozjak**

### CODE REVIEW

**Comment by pgporada** [comment]
@mkozjak I'm going merge this in, but will run the https://github.com/hashivim/vim-terraform/blob/master/update_automagic.sh script to get all the latest resources etc added in.

**Comment by pgporada** [comment]
Thank you!

**Comment by mkozjak** [comment]
> @mkozjak I'm going merge this in, but will run the https://github.com/hashivim/vim-terraform/blob/master/update_automagic.sh script to get all the latest resources etc added in.

Ok, you can ignore #75 then! Thanks!

**Comment by mkozjak** [comment]
For some reason, this does not work with the latest version.

screen shot 2018-12-24 at 09 35 26

Some other examples that are not highlighted:
```
google_compute_route
google_dns_managed_zone
google_compute_global_address
google_compute_backend_bucket
```

**Comment by pgporada** [comment]
@mkozjak All of this should be fixed now. Merry Christmas!

**Comment by mkozjak** [comment]
@pgporada: This one doesn't work for some reason, anymore. Having latest versions of everything.

**Comment by pgporada** [comment]
I've expanded the regex in `update_resources.rb` to catch whatever the hell it is Google is doing in their `terraform-provider-google`. This caught _a lot_ of missing resources. Could you pull and check again?

**Comment by pgporada** [comment]
https://github.com/hashivim/vim-terraform/commit/382d9fbf59b6ebf58402b9d8b6540028dae5c4af#diff-0177bdb843fa9e16684f224e10c7bc7dR2009

**Comment by mkozjak** [comment]
Works, thanks!!

**Comment by pgporada** [comment]
Awesome!

**Pull request merged**
