### PR TITLE
Vim terminal should redraw after fmt

### PR DESCRIPTION
**Pull request by rsiwal**
[166] Vim terminal should redraw after terraform file is saved

### CODE REVIEW

**Comment by dimbleby** [comment]
If redraw after formatting is necessary, then I expect this change should go in the function that does the formatting; not on this autocmd.

But I am yet to understand why this is necessary.  I format terraform files through vim regularly and have never felt the need to redraw...

**Comment by rajneshsiwal** [comment]
My test file without fmt is :  
```
provider "aws" {
          region = "us-west-2"
}
```
After fmt is
```
          region = "us-west-2"
} region = "us-west-2"
```
Here are the URLs of snapshots
PRE:
https://snipboard.io/tvGsuz.jpg
POST writing the file
https://snipboard.io/G1j3lR.jpg

If I redraw the window, it gets fixed.

**Comment by dimbleby** [comment]
I cannot reproduce: formatting the file, and formatting on save, both work exactly as expected for me.

I think this plugin has enough users that it's likely that whatever is going on here is something specific to your environment: maybe the vim version, or the terminal, or other plugins, or I don't know what.

If you're up for debugging I'd suggest:

- working manually through the steps that we do on formatting - [here](https://github.com/hashivim/vim-terraform/blob/814a21db89f742c3ea492c69c5a2bfecded1aeb3/autoload/terraform.vim#L7-L32)
- varying things like terminal, vim version etc, to clarify what combination of things is needed to create the problem.

In the long run that should be more valuable than working around the issue one plugin at a time...

**Comment by dimbleby** [comment]
Gonna close this one down, do feel free to open a fresh issue or MR if you want to make the case that this really is the right place to fix what you're seeing.

**Pull request closed without merging**
