### PR TITLE
Updated for terraform 0.12.20

### PR DESCRIPTION
**Pull request by pgporada**
Azurerm resources need to be investigated.

### CODE REVIEW

**Comment by dimbleby** [comment]
I wonder whether having these lists of possible data types and resources is worth it.  I can't imagine it's good for the performance of the syntax, and it looks like we've now got a maintenance issue...

Perhaps we'd be better off just assuming that anything that appeared in the right place was valid, and leaving it to terraform (via `terraform validate` or whatever) to say otherwise.

Indeed, I suppose that unknown values *are* valid syntax: we can't know what private plugins people might be using.  And almost all of the known values are not in fact valid if you haven't declared the appropriate provider - which we make no effort to check.

All of which is to say: we might reasonably think that eg detecting invalid resources is a job for a linter, not for a Vim syntax.

**Comment by pgporada** [comment]
I will defer to you for what you think is the best path forward. There is a maintenance burden when some upstream provider changes the way their files are structured.

**Comment by dimbleby** [comment]
Well, so long as you're willing to keep shouldering that burden, I have no reason to complain about it.

Still, if you're open to the idea of abandoning this, maybe I'll try prototyping that one day and see how it turns out.

It's one of those things that's been vaguely floating around in my mind for some time; don't bank on seeing anything happen soon...!

**Comment by pgporada** [comment]
I'm ok with that burden. It's maybe an hour of work the (twice now) times it happens. I think the real work is all of the time effort that you've put into this project and that really blows my mind.

**Pull request merged**
