### PR TITLE
set tab width to 2 spaces

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by pgporada** [comment]
Hey, thanks for taking a look at this! 

We already implement this via the following lines. This can be enabled via your vimrc by adding the following option per the [readme](https://github.com/hashivim/vim-terraform/blob/master/README.md#usage).
```
let g:terraform_align=1
```
https://github.com/hashivim/vim-terraform/blob/2d9343c7165acbb6225017a9da8baf63bbd27a26/after/ftplugin/terraform.vim#L62-L67

**Comment by drAlberT** [comment]
Hi,
  yes I already enabled that, but apparently nothing happened ..  uhmm .. I'm going to double check

**Comment by drAlberT** [comment]
Just checked.
I can **confirm** that only setting `terraform_align=`1 isn't enough.

For example indenting hitting `>` twice will use 4 spaces .. while appling this patch it behaves as expected (it uses 2 spaces).

Donno why the code you pointed isn't already doing the job anyway

**Comment by pgporada** [comment]
That's funky. Thanks for investigating!

**Comment by pgporada** [comment]
I'll get a test put together soonish and then get this merged.

**Comment by drAlberT** [comment]
Any news @pgporada ?

**Comment by pgporada** [comment]
I merged a change into master that should fix this.

**Pull request closed without merging**
