### PR TITLE
Make sure the command is called from the correct path

### PR DESCRIPTION
**Pull request by svanharmelen**
Terraform always tries to use relative paths[1][2] which can cause unexpected behavior in combination with how vim is automatically dereferencing symlinks.

You can see the problem by running `:pwd` and `:echo system('pwd')`. Both commands will show different paths which is the root cause of this problem.

This PR fixes the problem by making sure the command is always executed from the same directy as vim uses to reference the file.

Additionally I added `-no-color` to the command to prevent all the ANSI escape codes in any error output. The `-no-color` option has always been available for the `fmt` subcommand, but it just wasn't documented. I opened a PR for that as well on the Terraform repo (https://github.com/hashicorp/terraform/pull/22320)

[1] https://github.com/hashicorp/terraform/blob/master/command/fmt.go#L125
[2] https://github.com/hashicorp/terraform/blob/master/command/meta_config.go#L25

### CODE REVIEW

**Comment by dimbleby** [comment]
`-no-color` is a great find, and clearly we should do that whatever.

However, I think I prefer the simplification of #100, over the slight extra complication here.  So I'm inclined to merge that one rather than this.

Shout if you think that's a mistake!

**Comment by svanharmelen** [comment]
Closing this PR in favor of #100 👍

**Comment by svanharmelen** [comment]
@dimbleby I understand I need to rebase this, but I really really think we should revert to this solution instead of the one you merged now.

After using it for a bit today I now understand why it was previously using the tmp file solution. The solution you now merged messes up your undo chain by inserting an undo which you don’t expect.

This feels really strange and wrong as the first undo now takes you to the top of the file without actually undoing anything. Only after the second undo action it actually undo’s what you would expect.

So are you going to revert and update stuff (assuming you agree the current solution is not optimal and should be changed), of do you want me to rebase this PR on current master?

Thanks!

**Comment by dimbleby** [comment]
Ugh, it's certainly undesired behavior to make a mess of 'undo'.

I reckon the current implementation can be fixed with [this trick](https://vim.fandom.com/wiki/Restore_the_cursor_position_after_undoing_text_change_made_by_a_script).

It's a bit icky, and at some point there's a danger that the 'simpler' new implementation is not simpler at all.  But I think we're still on the right side of that.

**Comment by dimbleby** [comment]
#105

**Comment by svanharmelen** [comment]
@dimbleby I rebased this PR and prefer to use this solution as I believe it is more robust as it's already tested in other, heavily used (e.g. vim-go, vim-hclfmt), vim plugins.

**Comment by dimbleby** [comment]
I think I want to continue down the other path, for now at least.  I'm definitely open to switching back if we find good reason to do so.

As I commented in https://github.com/hashivim/vim-terraform/pull/106#discussion_r310961106, the implementation here is not without problems of its own.

(Actually the only bug that I know that either of them has at the moment is that this one unexpectedly writes the file to disk.  That's fixable, at the cost of further complication).

So I prefer to stick with the simpler approach, while agreeing that the latest fix is indeed an ugly one.

**Comment by svanharmelen** [comment]
@dimbleby please see my comments on PR #106. Unfortunately the changes in that PR don't solve the problem, it only makes it a bit less visible (no cursor jumping around anymore, but still no proper undo either).

**Pull request closed without merging**
